#!/usr/bin/env python

import praw
import json
import re
import time

class Responder(object):
    def __init__(self, configFilename = 'config.json'):
        config = json.load(open(configFilename))
        self.username = config['username']
        self.password = config['password']

        self.actions = {}
        for r, message in config['responses'].iteritems():
            self.actions[re.compile(r)] = message

        self.__r = praw.Reddit('Auto responder bot by /u/kragniz')
        self.__r.login(
                       self.username,
                       self.password
                      )

        self.messages = []

    def has_messages(self):
        self.messages = [m for m in self.__r.get_unread()]
        print len(self.messages)
        return len(self.messages) > 0

    def respond(self, message):
        for r, messageText in self.actions.iteritems():
            if r.match(message.subject):
                print str(r), 'matches', message.subject
                message.reply(messageText)
                message.mark_as_read()
                break

    def respond_to_messages(self):
        for m in self.messages:
            if not m.was_comment:
                self.respond(m)

if __name__ == '__main__':
    r = Responder()
    while True:
        time.sleep(1)
        try:
            if r.has_messages():
                r.respond_to_messages()
        except Exception, e:
            print e
